[package]
name = "dev_server"
version = "0.1.1"
edition = "2024"

[dependencies]
axum = { version = "0.8", default-features = false, features = [
    "ws",
    "tokio",
    "http1",
] }
clap = { version = "4", features = ["derive"] }
mime_guess = "2"
notify = "8"
tokio = { version = "1", features = ["full"] }
